### ISSUE TITLE
编译到32位，运行时会抛出panic

### ISSUE THREAD

**Issue by swzry** [aliyun/aliyun-log-go-sdk#81]
当使用了该包的程序，编译时指定了环境变量GOARCH=386或GOARCH=arm，编译后的程序运行时会抛出这样的panc:
`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11c70]

goroutine 5 [running]:
runtime/internal/atomic.goXadd64(0x24f27f4, 0x5c, 0x0, 0x5d45a8, 0x24f2780)
        D:/GoLang/Go/src/runtime/internal/atomic/atomic_arm.go:103 +0x1c
github.com/aliyun/aliyun-log-go-sdk/producer.(*LogAccumulator).addLogToProducerBatch(0x24daaa0, 0x24b3ea0, 0x11, 0x25373a0, 0x9, 0x0, 0x0, 0x24b3f40, 0x1f, 0x25373b7, ...)
        D:/GoLang/GoWork/src/github.com/aliyun/aliyun-log-go-sdk/producer/log_accumulator.go:67 +0x4ec
github.com/aliyun/aliyun-log-go-sdk/producer.(*Producer).SendLog(0x249aff0, 0x24b3ea0, 0x11, 0x25373a0, 0x9, 0x24b3f40, 0x1f, 0x25373b7, 0x7, 0x255cba0, ...)
        D:/GoLang/GoWork/src/github.com/aliyun/aliyun-log-go-sdk/producer/producer.go:137 +0xb4`
（stacktrace后面我自己的代码就不贴了）

推测是使用了go的原子操作在32位下的一个坑，一个朋友之前有遇到过这个问题，我推测这个库遇到的很可能也是这样的问题。该问题在go的atomic的文档中有描述：
https://golang.google.cn/pkg/sync/atomic/#pkg-note-BUG
`On x86-32, the 64-bit functions use instructions unavailable before the Pentium MMX.

On non-Linux ARM, the 64-bit functions use instructions unavailable before the ARMv6k core.

On ARM, x86-32, and 32-bit MIPS, it is the caller's responsibility to arrange for 64-bit alignment of 64-bit words accessed atomically. The first word in a variable or in an allocated struct, array, or slice can be relied upon to be 64-bit aligned.`

即，使用原子操作时要求64位对齐。

**Comment by swzry** [comment]
啊，抱歉，没有注意到你们9天前的更新修复了这个问题。更新了一下包，问题解决了。
